#!/usr/bin/env bash
# this script displays info about subdomains.

display_info() {
	local domain="$1"
	local sub_domain="$2"
	local destination

	if [[ -z "$sub_domain" ]]; then
		default_sub_domain=("www" "lb-01" "web-01" "web-02")
		for default_sub_domain in "${default_sub_domain[@]}"; do
			destination=$(dig +short "$default_sub_domain.$domain" | awk '{print $1}')
			echo "The subdomain $default_sub_domain is a A record and points to $destination"
		done
	else
		destination=$(dig +short "$sub_domain.$domain" | awk '{print $1}')
		echo "The subdomain $subdomain is A record and points to $destination"
	fi
}

domain="$1"
subdomain="$2"
display_info "$domain" "$subdomain"
