#!/usr/bin/env bash


# Install nginx
apt-get update
apt-get install -y nginx

# Configure redirection
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 http://example.com/;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
