#!/usr/bin/env bash
# This script displays the PID along with the process name

pids=$(pgrep -f bash)

for pid in $pids; do
    name=$(ps -p "$pid" -o comm=)
    printf "%-s %-s\n" "$pid" "$name"
done
