#!/usr/bin/env bash
# Configures servers with specified requirements.

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.2/127.0.0.1/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
rm ~/hosts.new
